# -*- coding: utf-8 -*-
"""Even no..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11QAeIPuPwuPdVjiRxChoReq5J0yAYLKl
"""

n=int(input("Enter a Even Number:"))
i=4
while(i<=n):
    print(i)
    i=i+2