# -*- coding: utf-8 -*-
"""For1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16uHIDDWQ07a7Stxt0FYPJipXuxIjW85Z
"""

x = int(input("enter a no."))
for y in range(1, 11):
  print(x * y)