# -*- coding: utf-8 -*-
"""len.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1La4X5B3b_LHLPHDUhd7ONGgPV6BmL4gE
"""

a="ram kumar"
print("Length of the string=",len(a))


a=input("Enter your Name:")
print("Length of the string=",len(a))