# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJ5GWrjKbZeG6xmymKtsMxk_jDTA9Mgb
"""

a=[]
for i in range(10):
    x=int(input("Enter a no.:"))
    a.append(x)
print(a)

a=["ram","shyam","sita","gita"]
a.append("mita")
print(a)