# -*- coding: utf-8 -*-
"""Marks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJQj2MLxvrpB804MdR1nuPFHfRQ7UdAR
"""

a=int(input("Enter 1st Number:"));
b=int(input("Enter 2nd Number:"));
c=int(input("Enter 3rd Number:"));
d=int(input("Enter 4th Number:"));
e=int(input("Enter 5th Number:"));
Total=a+b+c+d+e
Percent=(Total/500)*100
print("Total_Marks=",Total,"Percentage:",Percent);
if Percent>=80:
 print("GradeA");
elif Percent>=60:
 print("GradeB");
elif Percent>=40:
 print("GradeC");
else:
 print("GradeD");