# -*- coding: utf-8 -*-
"""Palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yqLkSjb9ylaze__6m8UHH8oyxlsjiTzD
"""

i=int(input("Enter a no.="))
temp=i
rev=0
while(i>0):
    rev=(rev*10)+i%10
    i=i//10
if(temp==rev):
    print("Palindrome No.")
else:
    print("Not Palindrome No.")