# -*- coding: utf-8 -*-
"""Positive,Neg.no.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UcVomHm3hNfbMCb4FKkqTfHNVHU02H64
"""

a=int(input("enter a 1st number:"));
if a>0:
 print("the number is positive");
elif a<0:
 print("the number is negative");
else:
 print("Zero");