# -*- coding: utf-8 -*-
"""Reverseno..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z6nPXwuiK9cC7RZMbY4oSXXIfg1Ufod-
"""

i=10
while(i>=1):
    print(i);
    i=i-1



n=int(input("Enter a number:"));
while(n>=1):
    print(n);
    n=n-1