# -*- coding: utf-8 -*-
"""sos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MTeKfRjaOYlztdAlJhDOl9uaSvu1F0d
"""

i=int(input("enter a no:"))
sum=0
while(i>0):
    x=(i%10)
    x=x*x
    sum=sum+x
    i=(i/10)
print("sum of square of each digit=",sum)