# -*- coding: utf-8 -*-
"""sum of even.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RPsTolvZjcFakvOglbfGusROHYDtN_YG
"""

n=int(input("Enter a Number:"));
sum=0
i=2
while (i<=n):
    sum=sum+i
    i=i+2
print("Sum of Even no.:",sum)