# -*- coding: utf-8 -*-
"""Table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SRM9CZLWo7AajEy5b5OuB6HRCsoX2c6I
"""

x=int(input("Enter a no."))
for y in range (1,11):
 n = x * y
 print(n)

for x in range (1,8):
  for y in range (1,11):
    n=x*y
    print(n)